-- Script SQL para la creación de tablas en Supabase
-- Proyecto: Red de Apoyo y Emergencia Ciudadana (Venezuela)

-- =========================================================================
-- 1. Tabla: reportes_emergencias
-- Almacena reportes activos de incidentes, personas desaparecidas o heridas.
-- =========================================================================
CREATE TABLE IF NOT EXISTS reportes_emergencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_id INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    direccion_exacta TEXT NOT NULL,
    nombre_completo TEXT,
    estado_persona TEXT NOT NULL DEFAULT 'Desaparecido', -- 'Atrapado / Herido', 'Desaparecido', 'A salvo en el sitio (Requiere asistencia)'
    detalles_emergencia TEXT,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    reportado_por_nombre TEXT,
    reportado_por_telefono TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) - Permitir inserciones públicas y lecturas públicas
ALTER TABLE reportes_emergencias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública en reportes_emergencias" 
ON reportes_emergencias FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública en reportes_emergencias" 
ON reportes_emergencias FOR SELECT 
USING (true);


-- =========================================================================
-- 2. Tabla: centros_acopio
-- Almacena puntos de recolección de ayuda humanitaria y suministros.
-- =========================================================================
CREATE TABLE IF NOT EXISTS centros_acopio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    direccion TEXT NOT NULL,
    insumos TEXT NOT NULL,
    horario TEXT,
    telefono TEXT,
    estado_id INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    verificado BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE centros_acopio ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública en centros_acopio" 
ON centros_acopio FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública en centros_acopio" 
ON centros_acopio FOR SELECT 
USING (true);


-- =========================================================================
-- 3. Tabla: voluntarios_medicos
-- Registro de personal médico y paramédico voluntario.
-- =========================================================================
CREATE TABLE IF NOT EXISTS voluntarios_medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo TEXT NOT NULL,
    especialidad TEXT NOT NULL,
    estado_id INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    dispone_transporte BOOLEAN DEFAULT FALSE,
    tiene_insumos BOOLEAN DEFAULT FALSE,
    telefono TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE voluntarios_medicos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública en voluntarios_medicos" 
ON voluntarios_medicos FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública en voluntarios_medicos" 
ON voluntarios_medicos FOR SELECT 
USING (true);


-- =========================================================================
-- OPCIONALES (Para soporte del componente ListaReportes si se activa a futuro)
-- =========================================================================

-- Tabla: reportes_victimas
CREATE TABLE IF NOT EXISTS reportes_victimas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo TEXT,
    estado_id INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    direccion_exacta TEXT NOT NULL,
    estado_persona TEXT NOT NULL,
    detalles_emergencia TEXT,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    reportado_por_nombre TEXT,
    reportado_por_telefono TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE reportes_victimas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserción pública en reportes_victimas" ON reportes_victimas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir lectura pública en reportes_victimas" ON reportes_victimas FOR SELECT USING (true);

-- Tabla: busqueda_familiares
CREATE TABLE IF NOT EXISTS busqueda_familiares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_buscado TEXT NOT NULL,
    cedula_buscado TEXT,
    estado_ultimo_visto INTEGER,
    detalles_adicionales TEXT,
    quien_busca_contacto TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE busqueda_familiares ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserción pública en busqueda_familiares" ON busqueda_familiares FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir lectura pública en busqueda_familiares" ON busqueda_familiares FOR SELECT USING (true);
